#spring:
#  profiles:
#    active: dev
#
#---
##开发环境
spring:
#  config:
#    activate:
#      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  key: adqwdqawddwq
  expiration: 7
server:
  port: 8080
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

#---
##测试环境
#spring:
#  config:
#    activate:
#      on-profile: test
#
#
#---
##生产环境
#spring:
#  config:
#    activate:
#      on-profile: pro
